# @name register-new-leader
POST http://localhost:3333/register/leader
Content-Type: application/json

{
    "name": "teste",
    "jobId": "b64fba12-0573-49bb-8086-71c4071c6d64"
}


###

# @name register-new-collaborator
POST http://localhost:3333/register/collaborator
Content-Type: application/json

{
    "name": "João",
    "salary": 1200,
    "jobId": "85c15527-5fa7-4bf7-8c07-402ee582d71e",
    "leaderId": ""
}