# @name register-new-leader
POST http://localhost:3333/register/leader
Content-Type: application/json

{
    "name": "Maria Joaquina",
    "jobId": "b64fba12-0573-49bb-8086-71c4071c6d64"
}


###

# @name register-new-collaborator
POST http://localhost:3333/register/collaborator
Content-Type: application/json

{
    "name": "Marina Silva",
    "salary": 1220,
    "jobId": "85c15527-5fa7-4bf7-8c07-402ee582d71e",
    "leaderId": "6b6a5e38-7e8c-4c7f-9b5e-8e2640fe5d9f"
}

###

# @name get-all-leaders
GET http://localhost:3333/leaders

###

# @name get-all-collaborators
GET http://localhost:3333/collaborators

