# @name register-new-leader
POST http://localhost:3333/register/leader
Content-Type: application/json

{
    "name": "Mário",
    "jobId": "9c18b29f-1fab-4d17-86c7-a63b2b660a7a"
}


###

# @name register-new-collaborator
POST http://localhost:3333/register/collaborator
Content-Type: application/json

{
    "name": "Ivanildo",
    "salary": 3200,
    "jobId": "3b4a5e47-d382-490f-ae4d-4421e2f608a8",
    "leaderId": "61b92c7d-3060-4026-bdb0-cb6147803595"
}

###

# @name get-all-leaders
GET http://localhost:3333/leaders

###

# @name get-all-collaborators
GET http://localhost:3333/collaborators


###

# @name auth
POST http://localhost:3333/login
Content-Type: application/json

{
    "username": "24ee0aed-c621-462d-b39a-092d9bcdb9e1",
    "password": "2ca06647-3b9a-4491-9d4a-93f621631dc9"
}


###

# @name get-all-leaders-by-influence
GET http://localhost:3333/influence







